version: '3.9'
services:
  db_myjob:
    image: mysql
    container_name: myjob_db_container
    environment:
      MYSQL_DATABASE: 'myjob'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: